// For all pokemon data
export const GET_POKEMON_DATA = 'GET_POKEMON_DATA';
export const SET_POKEMON_DATA = 'SET_POKEMON_DATA';
export const GET_POKEMON_DATA_ACTION = 'GET_POKEMON_DATA_ACTION';

// For pokemon moves
export const GET_POKEMON_MOVES = 'GET_POKEMON_MOVES';
export const SET_POKEMON_MOVES = 'SET_POKEMON_MOVES';
export const GET_POKEMON_MOVES_ACTION = 'GET_POKEMON_MOVES_ACTION';

// Get Pokemon details for a single pokemon
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const SET_POKEMON_DETAIL = 'SET_POKEMON_DETAIL';
export const GET_POKEMON_DETAIL_ACTION = 'GET_POKEMON_DETAIL_ACTION';

// Get All Pokemon items
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const SET_ALL_ITEMS = 'SET_ALL_ITEMS';
export const GET_ALL_ITEMS_ACTION = 'GET_ALL_ITEMS_ACTION';

// Move details data
export const GET_MOVE_DETAIL = 'GET_MOVE_DETAIL';
export const SET_MOVE_DETAIL = 'SET_MOVE_DETAIL';
export const GET_MOVE_DETAIL_ACTION = 'GET_MOVE_DETAIL_ACTION';

// Get Pokemon Types data
export const GET_POKEMON_TYPE_DATA = 'GET_POKEMON_TYPE_DATA';
export const SET_POKEMON_TYPE_DATA = 'SET_POKEMON_TYPE_DATA';
export const GET_POKEMON_TYPE_DATA_ACTION = 'GET_POKEMON_TYPE_DATA_ACTION';

// Get Pokemon Types detail data
export const GET_POKEMON_TYPE_DETAIL_DATA = 'GET_POKEMON_TYPE_DETAIL_DATA';
export const SET_POKEMON_TYPE_DETAIL_DATA = 'SET_POKEMON_TYPE_DETAIL_DATA';
export const GET_POKEMON_TYPE_DETAIL_DATA_ACTION = 'GET_POKEMON_TYPE_DETAIL_DATA_ACTION';

// Get Item details
export const GET_ITEM_DETAIL = 'GET_ITEM_DETAIL';
export const SET_ITEM_DETAIL = 'SET_ITEM_DETAIL';
export const GET_ITEM_DETAIL_ACTION = 'GET_ITEM_DETAIL_ACTION';





